WITH DWNT_ENE AS (
  SELECT HDRTYPECLASS,
        HDRTYPECODE,
        ASSETCODE,
        ASSETNAME,
        DOWNTIMETID,
        DOWNTIMEHID,
        DTPRODDAYSTART,
        DTREASON,
        DTREASONDESC,
        DTBEGINDATETIME,
        DTENDDATETIME,
        DTTOTALHRS,
        OPERATOR_UID,
        DTREMARKS,
        RECORDSRCTID,
        SOURCESYSTEM,
        DTENTRYDATETIME,
        LASTUPDATEID,
        TO_TIMESTAMP(LASTUPDATED) LASTUPDATED,
        current_timestamp() WHLOADDATEUTC
  FROM {{ ref('stg_ene_vw_downtime_merge') }} ENE
)
, DWNT_FDC AS (
  SELECT 
      HDRTYPECLASS
    , ASSETTYPECODE
    , ASSETCODE
    , ASSETNAME
    , DTBEGINDATETIME
    , DTENDDATETIME
    , DTTOTALHRS
    , DTREASON
    , DTREASONDESC
    , OPERATOR_UID
    , DTREMARKS
    , SOURCESYSTEM
    , LASTUPDATED
    , WHLOADDATEUTC
    , case when IS_ACTIVE then 1 else 0 end STATUS
  FROM {{ ref('stg_fdc_stg_dwntime_merge') }} CNTRL
)
, DWNT_MST AS (
SELECT MST.HDRTYPECLASS
  ,MST.ASSETTYPECODE
  ,MST.ASSETCODE
  ,MST.ASSETNAME
  ,MST.DOWNTIMETID
  ,MST.DOWNTIMEHID
  ,MST.DTPRODDAYSTART
  ,MST.DTREASON
  ,MST.DTREASONDESC
  ,MST.DTBEGINDATETIME
  ,MST.DTENDDATETIME
  ,MST.DTTOTALHRS
  ,MST.OPERATOR_UID
  ,MST.DTREMARKS
  ,MST.DTStatus
  ,MST.SOURCESYSTEM
  ,MST.RECORDSRCTID
  ,MST.DTENTRYDATETIME
  ,MST.LASTUPDATEID
  ,MST.LASTUPDATED
  ,MST.WHLOADDATEUTC
  ,MST.STATUS
FROM {{source('fdc_app_raw_merge', 'downtime_master')}} MST
)
, NEW_ENE AS
(
  SELECT ENE.*
  FROM DWNT_ENE ENE
  LEFT JOIN DWNT_MST MST ON ENE.ASSETCODE = MST.ASSETCODE AND TO_CHAR(ENE.DTBEGINDATETIME,'YYYYMMDD_HH24MISSFF') = TO_CHAR(MST.DTBEGINDATETIME,'YYYYMMDD_HH24MISSFF') and mst.STATUS = 1 
  WHERE MST.ASSETCODE IS NULL
)
, NEW_FDC AS
(
  SELECT FDC.*
  FROM DWNT_FDC FDC
  LEFT JOIN DWNT_MST MST ON FDC.ASSETCODE = MST.ASSETCODE AND TO_CHAR(FDC.DTBEGINDATETIME,'YYYYMMDD_HH24MISSFF') = TO_CHAR(MST.DTBEGINDATETIME,'YYYYMMDD_HH24MISSFF') AND fdc.STATUS = mst.STATUS 
  WHERE MST.ASSETCODE IS NULL 
)
, downtime_exceptions AS 
(
  --PREVIOUS-EXISTING-DOWNTIME
  SELECT 
    UUID_STRING() INCONSISTENCYUID, XCPTY.METRIC_DOMAIN_UID TYPEINCUID, MST.ASSETTYPECODE, MST.ASSETCODE AssetCode--,ENE.ASSETNAME
    ,FDC.DTBEGINDATETIME FDCBEGINDATETIME,FDC.DTENDDATETIME FDCENDDATETIME,FDC.DTTOTALHRS FDCTOTALHRS,FDC.DTREASON FDCREASON,FDC.DTREASONDESC FDCREASONDESC, FDC.OPERATOR_UID FDCOPERATOR_UID,FDC.DTREMARKS FDCREMARKS, FDC.SOURCESYSTEM FDCSOURCESYSTEM,FDC.LASTUPDATED FDCLASTUPDATED 
    ,ENE.DTBEGINDATETIME ENEBEGINDATETIME,ENE.DTENDDATETIME ENEENDDATETIME,ENE.DTTOTALHRS ENETOTALHRS,ENE.DTREASON ENEREASON,ENE.DTREASONDESC ENEREASONDESC,ENE.OPERATOR_UID ENEOPERATOR_UID,ENE.DTREMARKS ENEREMARKS, ENE.SOURCESYSTEM ENESOURCESYSTEM, ENE.LASTUPDATED ENELASTUPDATED
    ,MST.DTBEGINDATETIME MSTRBEGINDATETIME,MST.DTENDDATETIME MSTRENDDATETIME,MST.DTTOTALHRS MSTRTOTALHRS,MST.DTREASON MSTRREASON,MST.DTREASONDESC MSTRREASONDESC,MST.OPERATOR_UID MSTROPERATOR_UID,MST.DTREMARKS MSTRREMARKS, MST.SOURCESYSTEM MSTRSOURCESYSTEM, MST.LASTUPDATED MSTRLASTUPDATED
    ,null ERRORNUMBER,null ERRORDESC,null OUTCOME,'Pending' INCONSISTENCYSTATUS, CURRENT_TIMESTAMP() CREATIONDATE, CURRENT_TIMESTAMP() LASTUPDATED  
  FROM DWNT_MST MST 
  INNER JOIN DWNT_ENE ENE ON MST.ASSETCODE = ENE.ASSETCODE 
  AND ((ENE.DTBEGINDATETIME > MST.DTBEGINDATETIME AND ENE.DTBEGINDATETIME < MST.DTENDDATETIME)
        OR (MST.DTBEGINDATETIME > ENE.DTBEGINDATETIME AND MST.DTENDDATETIME < ENE.DTBEGINDATETIME))
  LEFT JOIN DWNT_FDC FDC ON ENE.ASSETCODE = FDC.ASSETCODE AND TO_CHAR(ENE.DTBEGINDATETIME,'YYYYMMDD_HH24MISSFF') = TO_CHAR(FDC.DTBEGINDATETIME,'YYYYMMDD_HH24MISSFF')
  cross join (
                SELECT METRIC_DOMAIN_UID 
                FROM {{ source('fdc_app_raw_merge', 'metric') }} M
                INNER JOIN {{ source('fdc_app_raw_merge', 'metric_domain') }} MD ON M.METRIC_UID =MD.METRIC_UID
                WHERE METRIC_CODE ='MTR193'
                AND UPPER(METRIC_DOMAIN_TEXT) = 'PREVIOUS EXISTING DOWNTIME'
              ) XCPTY
  WHERE MST.STATUS =1
  UNION ALL
  ----MISSING-DATA-IN-ENERTIA
  SELECT 
    UUID_STRING() INCONSISTENCYUID, XCPTY.METRIC_DOMAIN_UID TYPEINCUID, ENE.HDRTYPECODE,ENE.ASSETCODE--,ENE.ASSETNAME
    ,FDC.DTBEGINDATETIME FDCBEGINDATETIME,FDC.DTENDDATETIME FDCENDDATETIME,FDC.DTTOTALHRS FDCTOTALHRS,FDC.DTREASON FDCREASON,FDC.DTREASONDESC FDCREASONDESC, FDC.OPERATOR_UID FDCOPERATOR_UID,FDC.DTREMARKS FDCREMARKS, FDC.SOURCESYSTEM FDCSOURCESYSTEM,FDC.LASTUPDATED FDCLASTUPDATED 
    ,ENE.DTBEGINDATETIME ENEBEGINDATETIME,ENE.DTENDDATETIME ENEENDDATETIME,ENE.DTTOTALHRS ENETOTALHRS,ENE.DTREASON ENEREASON,ENE.DTREASONDESC ENEREASONDESC,ENE.OPERATOR_UID ENEOPERATOR_UID,ENE.DTREMARKS ENEREMARKS, ENE.SOURCESYSTEM ENESOURCESYSTEM, ENE.LASTUPDATED ENELASTUPDATED
    ,MST.DTBEGINDATETIME MSTRBEGINDATETIME,MST.DTENDDATETIME MSTRENDDATETIME,MST.DTTOTALHRS MSTRTOTALHRS,MST.DTREASON MSTRREASON,MST.DTREASONDESC MSTRREASONDESC, MST.OPERATOR_UID MSTROPERATOR_UID,MST.DTREMARKS MSTRREMARKS,MST.SOURCESYSTEM MSTRSOURCESYSTEM, MST.LASTUPDATED MSTRLASTUPDATED
    ,null ERRORNUMBER,null ERRORDESC,null OUTCOME,'Pending' INCONSISTENCYSTATUS, CURRENT_TIMESTAMP() CREATIONDATE, CURRENT_TIMESTAMP() LASTUPDATED
  FROM  DWNT_ENE ENE
  LEFT JOIN DWNT_MST MST  ON MST.ASSETCODE = ENE.ASSETCODE AND TO_CHAR(MST.DTBEGINDATETIME,'YYYYMMDD_HH24MISSFF') = TO_CHAR(ENE.DTBEGINDATETIME,'YYYYMMDD_HH24MISSFF')
  LEFT JOIN DWNT_FDC FDC ON ENE.ASSETCODE = FDC.ASSETCODE AND TO_CHAR(ENE.DTBEGINDATETIME,'YYYYMMDD_HH24MISSFF') = TO_CHAR(FDC.DTBEGINDATETIME,'YYYYMMDD_HH24MISSFF')
  LEFT JOIN (
              SELECT METRIC_DOMAIN_CODE,METRIC_DOMAIN_TEXT 
              FROM {{ source('fdc_app_raw_merge', 'metric_domain') }} MD
              INNER JOIN {{ source('fdc_app_raw_merge', 'metric') }} M ON MD.METRIC_UID = M.METRIC_UID
              WHERE M.METRIC_CODE ='MTR085'
            ) RSN on trim(ENE.DTREASON) = trim(RSN.METRIC_DOMAIN_CODE)
  cross join (
                SELECT METRIC_DOMAIN_UID 
                FROM {{ source('fdc_app_raw_merge', 'metric') }} M
                INNER JOIN {{ source('fdc_app_raw_merge', 'metric_domain') }} MD ON M.METRIC_UID =MD.METRIC_UID
                WHERE METRIC_CODE ='MTR193'
                AND UPPER(METRIC_DOMAIN_TEXT) = 'MISSING DATA IN ENERTIA'
              ) XCPTY
  WHERE ENE.DTBEGINDATETIME >=TO_DATE(convert_timezone('US/Central', CURRENT_TIMESTAMP())) OR RSN.METRIC_DOMAIN_CODE IS NULL OR (ENE.DTBEGINDATETIME > ENE.DTENDDATETIME)
  UNION ALL
  ----NEW-RECORD-INCONSISTENCY
  SELECT 
    UUID_STRING() INCONSISTENCYUID, XCPTY.METRIC_DOMAIN_UID TYPEINCUID, FDC.ASSETTYPECODE,FDC.ASSETCODE--,ENE.ASSETNAME
    ,FDC.DTBEGINDATETIME FDCBEGINDATETIME,FDC.DTENDDATETIME FDCENDDATETIME,FDC.DTTOTALHRS FDCTOTALHRS,FDC.DTREASON FDCREASON,FDC.DTREASONDESC FDCREASONDESC, FDC.OPERATOR_UID FDCOPERATOR_UID,FDC.DTREMARKS FDCREMARKS, FDC.SOURCESYSTEM FDCSOURCESYSTEM, FDC.LASTUPDATED FDCLASTUPDATED
    ,ENE.DTBEGINDATETIME ENEBEGINDATETIME,ENE.DTENDDATETIME ENEENDDATETIME,ENE.DTTOTALHRS ENETOTALHRS,ENE.DTREASON ENEREASON,ENE.DTREASONDESC ENEREASONDESC, ENE.OPERATOR_UID ENEOPERATOR_UID,ENE.DTREMARKS ENEREMARKS, ENE.SOURCESYSTEM ENESOURCESYSTEM,ENE.LASTUPDATED ENELASTUPDATED
    ,null MSTRBEGINDATETIME,null MSTRENDDATETIME,null MSTRTOTALHRS,null MSTRREASON,null MSTRREASONDESC,NULL MSTROPERATOR_UID,null MSTRREMARKS, NULL MSTRSOURCESYSTEM,NULL MSTRLASTUPDATED
    ,null ERRORNUMBER,null ERRORDESC,null OUTCOME,'Pending' INCONSISTENCYSTATUS,CURRENT_TIMESTAMP() CREATIONDATE, CURRENT_TIMESTAMP() LASTUPDATE
  FROM NEW_FDC FDC
  INNER JOIN NEW_ENE ENE ON FDC.ASSETCODE = ENE.ASSETCODE AND TO_CHAR(FDC.DTENDDATETIME,'YYYYMMDD_HH24MISSFF') = TO_CHAR(ENE.DTENDDATETIME,'YYYYMMDD_HH24MISSFF')
  CROSS JOIN (
                SELECT METRIC_DOMAIN_UID 
                FROM {{ source('fdc_app_raw_merge', 'metric') }} M
                INNER JOIN {{ source('fdc_app_raw_merge', 'metric_domain') }} MD ON M.METRIC_UID =MD.METRIC_UID
                WHERE METRIC_CODE ='MTR193'
                AND UPPER(METRIC_DOMAIN_TEXT) = 'NEW RECORD INCONSISTENCY'
              ) XCPTY
  WHERE FDC.DTBEGINDATETIME <> ENE.DTBEGINDATETIME  
    AND (( FDC.DTBEGINDATETIME between ENE.DTBEGINDATETIME and ENE.DTENDDATETIME) or ( ENE.DTBEGINDATETIME between FDC.DTBEGINDATETIME and FDC.DTENDDATETIME))
  UNION ALL
  --NON-SYSTEM UPDATE_ID 
  SELECT 
    UUID_STRING() INCONSISTENCYUID, XCPTY.METRIC_DOMAIN_UID TYPEINCUID, ENE.HDRTYPECODE,ENE.ASSETCODE--,ENE.ASSETNAME
    ,FDC.DTBEGINDATETIME FDCBEGINDATETIME,FDC.DTENDDATETIME FDCENDDATETIME,FDC.DTTOTALHRS FDCTOTALHRS,FDC.DTREASON FDCREASON,FDC.DTREASONDESC FDCREASONDESC, FDC.OPERATOR_UID FDCOPERATOR_UID, FDC.DTREMARKS FDCREMARKS, FDC.SOURCESYSTEM FDCSOURCESYSTEM, FDC.LASTUPDATED FDCLASTUPDATED
    ,ENE.DTBEGINDATETIME ENEBEGINDATETIME,ENE.DTENDDATETIME ENEENDDATETIME,ENE.DTTOTALHRS ENETOTALHRS,ENE.DTREASON ENEREASON,ENE.DTREASONDESC ENEREASONDESC, ENE.OPERATOR_UID ENEOPERATOR_UID, ENE.DTREMARKS ENEREMARKS, ENE.SOURCESYSTEM ENESOURCESYSTEM, ENE.LASTUPDATED ENELASTUPDATED
    ,MST.DTBEGINDATETIME MSTRBEGINDATETIME,MST.DTENDDATETIME MSTRENDDATETIME,MST.DTTOTALHRS MSTRTOTALHRS,MST.DTREASON MSTRREASON,MST.DTREASONDESC MSTRREASONDESC, MST.OPERATOR_UID MSTROPERATOR_UID, MST.DTREMARKS MSTRREMARKS, MST.SOURCESYSTEM MSTRSOURCESYSTEM, MST.LASTUPDATED MSTRLASTUPDATED
    ,null ERRORNUMBER,null ERRORDESC,null OUTCOME,'Pending' INCONSISTENCYSTATUS, CURRENT_TIMESTAMP() CREATIONDATE, CURRENT_TIMESTAMP() LASTUPDATED
  FROM DWNT_ENE ENE
    LEFT JOIN DWNT_FDC FDC ON ENE.ASSETCODE = FDC.ASSETCODE AND TO_CHAR(ENE.DTBEGINDATETIME,'YYYYMMDD_HH24MISSFF') = TO_CHAR(FDC.DTBEGINDATETIME,'YYYYMMDD_HH24MISSFF') AND FDC.STATUS =1
    LEFT JOIN DWNT_MST MST ON ENE.ASSETCODE = MST.ASSETCODE AND TO_CHAR(ENE.DTBEGINDATETIME,'YYYYMMDD_HH24MISSFF') = TO_CHAR(MST.DTBEGINDATETIME,'YYYYMMDD_HH24MISSFF') AND MST.STATUS =1
  CROSS JOIN (
                SELECT METRIC_DOMAIN_UID , UPPER(METRIC_DOMAIN_TEXT)
                FROM {{ source('fdc_app_raw_merge', 'metric') }}  M
                INNER JOIN {{ source('fdc_app_raw_merge', 'metric_domain') }}  MD ON M.METRIC_UID =MD.METRIC_UID
                WHERE METRIC_CODE ='MTR193'
                AND UPPER(METRIC_DOMAIN_TEXT) = 'END DATE INCONSISTENCY FROM ENERTIA'
              ) XCPTY
  WHERE MST.ASSETCODE IS NOT NULL AND TO_DATE(ENE.DTENDDATETIME) <> TO_DATE('12-31-2078','MM-DD-YYYY') AND NULLIF(TRIM(ENE.LASTUPDATEID),'') IS NULL
  
)
SELECT * 
FROM  downtime_exceptions
