--==============================================
-- VISIT_METRIC (TESTING)
--==============================================
WITH DT_VM_UID as (
        SELECT 
            DOWNTIME_UID METRIC_VALUE_UID
            , ASSET_UID
            , VISIT_METRIC_BEGIN_DATE_UID DT_VISIT_METRIC_UID
            , LAST_UPDATE
            , BEGIN_DATETIME
            , METRIC_DOMAIN_UID
            , COALESCE(END_DATETIME,TO_DATE('12-31-2078','MM-DD-YYYY')) END_DATETIME
            , 'MTR052' METRIC_CODE
            , DTSTATUS
            , IS_ACTIVE
            , SOURCE_SYSTEM
            , CREATION_DATE
        FROM   {{ ref('fdc_stg_downtime_merge') }} 
        UNION
        SELECT 
            DOWNTIME_UID
            , ASSET_UID
            , VISIT_METRIC_DTREASON_UID
            , LAST_UPDATE
            , BEGIN_DATETIME
            , METRIC_DOMAIN_UID
            , COALESCE(END_DATETIME,TO_DATE('12-31-2078','MM-DD-YYYY')) END_DATETIME
            , 'MTR085' METRIC_CODE
            , DTSTATUS
            , IS_ACTIVE
            , SOURCE_SYSTEM
            , CREATION_DATE
        FROM   {{ ref('fdc_stg_downtime_merge') }} 
        UNION
        SELECT 
            DOWNTIME_UID 
            , ASSET_UID
            , VISIT_METRIC_END_DATE_UID
            , LAST_UPDATE
            , BEGIN_DATETIME
            , METRIC_DOMAIN_UID
            , COALESCE(END_DATETIME,TO_DATE('12-31-2078','MM-DD-YYYY')) END_DATETIME
            , 'MTR051' METRIC_CODE
            , DTSTATUS
            , IS_ACTIVE
            , SOURCE_SYSTEM
            , CREATION_DATE
        FROM  {{ ref('fdc_stg_downtime_merge') }} 
        WHERE COALESCE(END_DATETIME,TO_DATE('12-31-2078','MM-DD-YYYY')) <> TO_DATE('12-31-2078','MM-DD-YYYY') 
    ) 
,VISIT_ASSET_TEM AS (
      SELECT  ASSET_UID, to_date(VISIT_ASSET_DATE) VISIT_ASSET_DATE, min(VISIT_ASSET_UID)VISIT_ASSET_UID
      FROM {{source('fdc_app_raw_merge', 'visit_asset')}} 
      GROUP BY ASSET_UID, to_date(VISIT_ASSET_DATE) 
)  
, VISIT_ASSET_TEM_ALL AS (
    SELECT  DT.ASSET_UID, to_date(COALESCE(VAT.VISIT_ASSET_DATE,DT.BEGIN_DATETIME)) AS VISIT_ASSET_DATE, MIN(COALESCE(VAT.VISIT_ASSET_UID, UUID_STRING())) VISIT_ASSET_UID
    FROM       DT_VM_UID    DT 
    LEFT JOIN  VISIT_ASSET_TEM   VAT ON DT.ASSET_UID=VAT.ASSET_UID AND TO_DATE(CASE WHEN DT.METRIC_CODE IN ('MTR052','MTR085') THEN DT.BEGIN_DATETIME ELSE DT.END_DATETIME END)=TO_DATE(VAT.VISIT_ASSET_DATE)
    WHERE DT.METRIC_CODE='MTR052'
    GROUP BY DT.ASSET_UID, to_date(COALESCE(VAT.VISIT_ASSET_DATE,DT.BEGIN_DATETIME))
)    
    SELECT 
        COALESCE(VM.VISIT_METRIC_UID, DT_VISIT_METRIC_UID) VISIT_METRIC_UID
        ,M.METRIC_UID
        ,COALESCE(VM.VISIT_ASSET_UID,VAT.VISIT_ASSET_UID, UUID_STRING()) VISIT_ASSET_UID
        ,COALESCE(VM.VISIT_METRIC_DATE, TO_DATE(CASE WHEN DT.METRIC_CODE IN ('MTR052','MTR085') THEN DT.BEGIN_DATETIME ELSE DT.END_DATETIME END)) VISIT_METRIC_DATE
        --,COALESCE(VM.VISIT_METRIC_DATE, DT.LAST_UPDATE) VISIT_METRIC_DATE
        ,NULL VISIT_VALUE_NUM
        ,NULL VISIT_VALUE_TEXT
        ,CASE WHEN DT.METRIC_CODE = 'MTR051' THEN DT.END_DATETIME WHEN DT.METRIC_CODE = 'MTR052' THEN DT.BEGIN_DATETIME ELSE NULL END VISIT_VALUE_DATE
        ,CASE WHEN DT.METRIC_CODE = 'MTR085' THEN DT.METRIC_DOMAIN_UID ELSE NULL END METRIC_DOMAIN_UID
        ,NULL VISIT_ASSET_CODE
        ,NULL VISIT_VAL_CRRYFRD
        ,NULL PICTURE_URL
        ,DT.LAST_UPDATE
        ,COALESCE(VM.ADMIN_ENTRY_FLG,0) ADMIN_ENTRY_FLG
        ,COALESCE(VM.UPDATED_BY_UID,(SELECT OPERATOR_UID FROM {{source('fdc_app_raw_merge', 'operator')}} WHERE OPERATOR_CODE='-1')) as UPDATED_BY_UID
       -- ,VM.UPDATED_BY_UID UPDATED_BY_UID
        ,DT.SOURCE_SYSTEM
        ,case when DT.IS_ACTIVE = true then 1 else 0 end STATUS
        ,CASE WHEN DT.SOURCE_SYSTEM='SL-FDC' THEN 'MANUAL' ELSE 'ELECTRONIC' END  ENTRY_TYPE
        ,null VISIT_VALUE_CMMNT
        ,null VISIT_MANAGER_APPROVE
        ,DT.DTSTATUS
        ,DT.METRIC_VALUE_UID
        ,convert_timezone('America/Los_Angeles' , 'UTC', CURRENT_DATE()) LAST_SYNC_DATETIME
        , COALESCE(VM.CREATION_DATE, DT.CREATION_DATE) CREATION_DATE
    FROM       DT_VM_UID                               DT 
    LEFT JOIN  VISIT_ASSET_TEM_ALL                               VAT ON DT.ASSET_UID=VAT.ASSET_UID AND TO_DATE(CASE WHEN DT.METRIC_CODE IN ('MTR052','MTR085') THEN DT.BEGIN_DATETIME ELSE DT.END_DATETIME END)=TO_DATE(VAT.VISIT_ASSET_DATE)
    LEFT JOIN  {{source('fdc_app_raw_merge', 'visit_metric')}}   VM   ON DT.DT_VISIT_METRIC_UID   = VM.VISIT_METRIC_UID
    LEFT JOIN  {{source('fdc_app_raw_merge', 'visit_asset')}}    VA   ON VM.VISIT_ASSET_UID       = VA.VISIT_ASSET_UID 
    LEFT JOIN  {{source('fdc_app_raw_merge', 'visit_site')}}     VS   ON VA.VISIT_SITE_UID        = VS.VISIT_SITE_UID
    LEFT JOIN  {{source('fdc_app_raw_merge', 'metric')}}         M    ON DT.METRIC_CODE           = M.METRIC_CODE