WITH ALLDWTM AS (
  SELECT VM.VISIT_METRIC_UID,
         F.VISIT_ASSET_UID,
         VM.METRIC_VALUE_UID,
         A.ASSET_UID,
         F.VISIT_ASSET_DATE,
         D.METRIC_CODE,
         D.METRIC_NAME,
         VM.VISIT_VALUE_TEXT,
         VM.VISIT_VALUE_DATE,
         CASE
              WHEN VM.VISIT_VALUE_DATE IS NOT NULL THEN CAST(TO_TIMESTAMP(VM.VISIT_VALUE_DATE) AS VARCHAR(50)) 
              WHEN VM.VISIT_VALUE_TEXT IS NOT NULL THEN nullif(trim(VM.VISIT_VALUE_TEXT),'') 
              WHEN VM.METRIC_DOMAIN_UID IS NOT NULL THEN CAST(MD.METRIC_DOMAIN_CODE AS VARCHAR(50))
              ELSE NULL
         END METRIC_VALUE
         , VM.LAST_UPDATE
		 , vs.operator_uid
		 , VM.DTSTATUS
     , VM.LAST_SYNC_DATETIME
  FROM  {{source('fdc_app_raw_merge', 'visit_metric')}}  VM 
    INNER JOIN {{source('fdc_app_raw_merge', 'visit_asset')}} AS F ON VM.VISIT_ASSET_UID = F.VISIT_ASSET_UID 
    INNER JOIN {{source('fdc_app_raw_merge', 'asset')}} AS A ON A.ASSET_UID = F.ASSET_UID
    INNER JOIN {{source('fdc_app_raw_merge', 'asset_class')}} AS B ON A.ASSET_CLASS_UID = B.ASSET_CLASS_UID
    INNER JOIN {{source('fdc_app_raw_merge', 'visit_site')}} AS VS ON F.VISIT_SITE_UID = VS.VISIT_SITE_UID
    INNER JOIN {{source('fdc_app_raw_merge', 'metric')}} AS D ON VM.METRIC_UID = D.METRIC_UID
    LEFT JOIN  {{source('fdc_app_raw_merge', 'metric_domain')}} AS MD ON MD.METRIC_DOMAIN_UID = VM.METRIC_DOMAIN_UID
  WHERE D.METRIC_CODE IN ('MTR051','MTR052','MTR085')
	AND VM.STATUS =1 
	--AND CASE
	--          WHEN VM.VISIT_VALUE_DATE IS NOT NULL THEN CAST(TO_TIMESTAMP(VM.VISIT_VALUE_DATE) AS VARCHAR(50)) 
  --            WHEN VM.VISIT_VALUE_TEXT IS NOT NULL THEN nullif(trim(VM.VISIT_VALUE_TEXT),'') 
  --            WHEN VM.METRIC_DOMAIN_UID IS NOT NULL THEN CAST(MD.METRIC_DOMAIN_CODE AS VARCHAR(50))
  --            ELSE NULL
  --       END IS NOT NULL
)
, DTPIVOT as
( 
  SELECT BG.ASSET_UID, TO_TIMESTAMP(BG.METRIC_VALUE) DTBEGINDATETIME, RS.METRIC_VALUE DTREASON, COALESCE(TO_TIMESTAMP(DN.METRIC_VALUE),TO_TIMESTAMP('2078-12-31')) DTENDDATETIME
         , BG.OPERATOR_UID, COALESCE(DT.SOURCE_SYSTEM, 'SL-FDC') SOURCESYSTEM, BG.METRIC_VALUE_UID, BG.DTSTATUS, 
         CASE WHEN DN.LAST_UPDATE IS NULL THEN BG.LAST_UPDATE ELSE DN.LAST_UPDATE END  LASTUPDATED, DT.CREATION_DATE , DT.IS_ACTIVE
         , CASE WHEN DN.LAST_SYNC_DATETIME IS NULL THEN BG.LAST_SYNC_DATETIME ELSE DN.LAST_SYNC_DATETIME END LAST_SYNC_DATETIME
        --BG.VISIT_METRIC_UID, BG.ASSET_UID, BG.OPERATOR_UID, BG.VISIT_ASSET_DATE, BG.LAST_UPDATE, BG.DTSTATUS
        --,RS.VISIT_METRIC_UID, RS.ASSET_UID, RS.OPERATOR_UID, RS.VISIT_ASSET_DATE, RS.LAST_UPDATE, RS.DTSTATUS
        --,DN.VISIT_METRIC_UID, DN.ASSET_UID, DN.OPERATOR_UID, DN.VISIT_ASSET_DATE, DN.LAST_UPDATE, DN.DTSTATUS
  FROM {{source('fdc_app_raw_merge', 'fdc_downtime')}} DT
  INNER JOIN ALLDWTM BG ON BG.METRIC_VALUE_UID = DT.DOWNTIME_UID AND BG.METRIC_CODE IN ('MTR052') 
  INNER JOIN ALLDWTM RS ON RS.METRIC_VALUE_UID = DT.DOWNTIME_UID AND RS.METRIC_CODE IN ('MTR085')
  LEFT  JOIN ALLDWTM DN ON DN.METRIC_VALUE_UID = DT.DOWNTIME_UID AND DN.METRIC_CODE IN ('MTR051')
)
SELECT CASE WHEN ASSET_CLASS_NAME = 'Equipment' THEN 'Equip' ELSE 'Prop' END HDRTYPECLASS 
    ,CASE  WHEN ASSET_CLASS_NAME in ('Equipment','Salt Water Disposal') THEN 'FuelUse' WHEN ASSET_CLASS_NAME = 'Meter' then 'GasMtr' ELSE  ASSET_CLASS_NAME END ASSETTYPECODE
    ,ast.ASSET_CODE ASSETCODE
    ,NULL ASSETNAME
    --, VM.ASSET_UID
    , DTBEGINDATETIME
    , DTENDDATETIME
    ,CASE WHEN DTBEGINDATETIME <= DTENDDATETIME AND DTENDDATETIME IS NOT NULL THEN DATEDIFF(hour, DTBEGINDATETIME, DTENDDATETIME) when  DTENDDATETIME is null or DTENDDATETIME = TO_TIMESTAMP('2078-12-31') then DATEDIFF(hour, DTBEGINDATETIME, getdate()) ELSE NULL END DTTOTALHRS  
    , TRIM(DTREASON) DTREASON
    , MD.METRIC_DOMAIN_TEXT DTREASONDESC
    , VM.OPERATOR_UID
    , o.OPERATOR_NAME DTREMARKS
    , METRIC_VALUE_UID
    , DTStatus
    , SOURCESYSTEM
    , LASTUPDATED
    , convert_timezone( 'America/Los_Angeles' , 'UTC', current_timestamp())::timestamp_ntz WHLOADDATEUTC
    , VM.CREATION_DATE
    , VM.IS_ACTIVE
    , VM.LAST_SYNC_DATETIME
FROM DTPIVOT VM 
INNER JOIN {{source('fdc_app_raw_merge', 'asset')}} AS AST ON VM.ASSET_UID=AST.ASSET_UID
INNER JOIN {{source('fdc_app_raw_merge', 'site')}} AS ST ON AST.SITE_UID=ST.SITE_UID
INNER JOIN {{source('fdc_app_raw_merge', 'route')}} RT ON ST.ROUTE_UID=RT.ROUTE_UID
INNER JOIN {{source('fdc_app_raw_merge', 'operator')}} O ON VM.OPERATOR_UID = O.OPERATOR_UID
INNER JOIN {{source('fdc_app_raw_merge', 'asset_type')}} TY ON AST.ASSET_TYPE_UID=TY.ASSET_TYPE_UID
INNER JOIN {{source('fdc_app_raw_merge', 'asset_class')}} AC ON TY.ASSET_CLASS_UID=AC.ASSET_CLASS_UID
LEFT JOIN  (SELECT MD.METRIC_DOMAIN_CODE ,MD.METRIC_DOMAIN_TEXT 
            FROM {{source('fdc_app_raw_merge', 'metric_domain')}} MD 
            INNER JOIN  {{source('fdc_app_raw_merge', 'metric')}} M ON MD.METRIC_UID =M.METRIC_UID
            WHERE M.metric_code='MTR085') MD ON VM.DTREASON=MD.METRIC_DOMAIN_CODE 